### ISSUE TITLE
Security Group

### ISSUE THREAD

**Issue by sarathi190590** [azavea/terraform-aws-redis-elasticache#19]
There is no option for using the default security.
Also, I need alarm_actions as Optional Inputs.
Please help me.

**Comment by hectcastro** [comment]
Hey, @sarathi190590.

Our approach with security groups across our modules has been to create the security group, but not supply it with any rules. We have an output for the security group ID, which can be used with the `aws_security_group_rule` resource like:

```hcl
resource "aws_security_group_rule" "bastion_redis_egress" {
  type                     = "egress"
  from_port                = 6379
  to_port                  = 6379
  protocol                 = "tcp"
  security_group_id        = "${module.vpc.bastion_security_group_id}"
  source_security_group_id = "${module.broker.cache_security_group_id}"
}
```

Here, `broker` is an instance of this module.

**Comment by sarathi190590** [comment]
Hi @hectcastro,

Thank you for the update.

And also, I need alarm_actions as Optional Inputs. I don't want to create Cloudwatch for this. How to do that.

**Comment by hectcastro** [comment]
Unfortunately, `alarm_actions` is not an optional parameter for this module. If you wanted to setup a Redis cache cluster without CloudWatch alarms, I'd suggest using the `aws_elasticache_replication_group` resource directly.

**Comment by sarathi190590** [comment]
ok @hectcastro Thank you.
